### PR TITLE
(Corrected) Use AWS Secrets Manager

### PR DESCRIPTION
**Pull request by technicalex**

### CODE REVIEW

**Comment by technicalex** [comment]
You may wish to look at each commit in this pull request separately. The first commit updates the code to use AWS Secrets manager instead of a local `settings.py` file. The second commit allows local testing on a PostgreSQL database. The third commit is a minor fix for a low (no?) impact bug that's been around a long time.

**Comment by technicalex** [comment]
Documenting the steps I took to test these changes:

1. `virtualenv --clear venv`
2. `pip install -r requirements.txt`
3. `cp settings.py.example test_settings.py`
4. Edited test_settings.py to store local Postgres credentials
5. Started local Postgres database
6. `pytest`, looked for passing tests
7. Edited test_settings.py to set `DB_TYPE = ''`
8. `pytest`, looked for expected `InvalidDbTypeException`
9. **VERY IMPORTANT** Commented out lines 498 through 529 (inclusive) in ak_survey_results.py `main()` function, so that the function would simply instantiate `ak`, print output, and `return False`.
10. `python3 ak_survey_results.py` and looked for expected output:
```
running main
False FUNCTION
False PAGE_ID
False SINCE
False
```
11. `cp test_settings.py settings.py` to copy test settings into "real" settings file
12. Changed secret name in on line 29 of ak_survey_results.py to '' (e.g. `settings = get_settings(ARG_DEFINITIONS, '')`, forcing the script to get settings from `settings.py` instead of AWS Secrets Manager
13. `python3 ak_survey_results.py` and looked for expected output:
```
running main
survey_refresh_info FUNCTION
1 PAGE_ID
60 SINCE
False
```
14. Stopped local Postgres database

**Comment by technicalex** [comment]
After approval but before merging this pull request, I will re-deploy to AWS Lambda to ensure that the deployed code matches what we will have in main after merge.

**Comment by technicalex** [comment]
@ibrand, the changes in the first commit are what we deployed this morning.

**Comment by technicalex** [comment]
@sjwmoveon @codygordon, the problem with the first pull request was that I essentially made the changes in the wrong place. Knowing that AWS would supply secrets in a dictionary, I updated the class `AKSurveyResults` to use `settings` as a dictionary. Instead, I should have just updated the callers who instantiate `AKSurveyResults` (to run unit tests, to run from command line, and to run from Lambda) to use `settings` as a dictionary. Those callers transform `settings` before passing the settings to `AKSurveyResults`, so it's fine to leave all of that code as-is.

I'm sorry this is confusing. Let me know if you have any questions!

**Review by ibrand — APPROVED** [review]
🎉  thank you for the write up on the PR!

**Comment by technicalex** [comment]
I redeployed the Lambda from this branch and everything looks good! Merging now.

**Pull request merged**
